_target_: workspace.fixed_sequence_gvl_frame_gap_ws.RewindRewardWorkspace

cfg:
  general:
    # dataset specific
    project_name: "reward_model"
    task_name: "unload_dish_gvl"
    repo_id: Qianzhong-Chen/yam_unload_dish_reward_0911 
    state_norm_path: "/home/david_chen/rewind_tshirt/assets/fold_tshirt.json"
    camera_names:  [top_camera-images-rgb]
    seed: 42
    device: "cuda"        # "cpu" for debugging

  dataloader:
    batch_size: 32
    num_workers: 12 # nproc=32
    shuffle: True
    pin_memory: True
    persistent_workers: True

  val_dataloader:
    batch_size: 32
    num_workers: 12
    shuffle: False
    pin_memory: True
    persistent_workers: True

  rollout_dataloader:
    batch_size: 1 # don't change
    num_workers: 12
    shuffle: True
    pin_memory: True
    persistent_workers: True

  encoders:               
    # CLIP
    vision_ckpt: "openai/clip-vit-base-patch32"
    text_ckpt: "openai/clip-vit-base-patch32"

  model:
    d_model: 768          # CLS width of dinov2-base
    max_seq_len: 128
    n_layers: 6
    n_heads: 12
    dropout: 0.1
    horizon: 8
    n_obs_steps: 6
    state_dim: 14
    no_state: True
    dense_annotation: False # check the rule inside the dataset class to allign with progress
    resume_training: False
    model_path: ""

    # Sparse anno
    num_classes: 3 # num_classes = num_stage 
    annotation_list: [
        "grab the dish",
        "place the dish",
    ]
    

  optim:
    lr: 5e-5
    weight_decay: 5.0e-3
    betas: [0.9, 0.95]
    eps: 1.0e-8
    warmup_steps: 1000
    total_steps: 100_000

  train:
    num_epochs: 2
    grad_clip: 1.0
    log_every: 50        # steps
    eval_every: 1        # epochs
    save_every: 5_000     # steps
    val_portion: 0.1     # fraction of episodes for validation
    rollout_every: 10     # epoch
    rollout_steps: 10    # steps per rollout

  eval:
    run_times: 50        # number of rollouts
    video_run_times: 20 # number of episodes to evaluate in video
    raw_data_run_times: 36
    eval_frame_gap: 10
    # Dense
    ckpt_path: "/nfs_old/david_chen/reward_model_ckpt/dish_unloading/2025-09-13/07-42-43/unload_dish_gvl/checkpoints/reward_step_025000_loss_0.001.pt"
    raw_data_dir: ""

    
