_target_: workspace.fixed_sequence_multi_stage_frame_gap_ws.RewindRewardWorkspace

cfg:
  general:
    # dataset specific
    project_name: "reward_model"
    task_name: "unload_dish"
    repo_id: Qianzhong-Chen/yam_unload_dish_reward_0911
    state_norm_path: "/home/david_chen/rewind_tshirt/assets/fold_tshirt.json"
    camera_names:  [left_camera-images-rgb, right_camera-images-rgb, top_camera-images-rgb]
    seed: 42
    device: "cuda"        # "cpu" for debugging

  dataloader:
    batch_size: 64
    num_workers: 12 # nproc=32
    shuffle: True
    pin_memory: True
    persistent_workers: True

  val_dataloader:
    batch_size: 16
    num_workers: 4
    shuffle: False
    pin_memory: True
    persistent_workers: True

  rollout_dataloader:
    batch_size: 1 # don't change
    num_workers: 12
    shuffle: True
    pin_memory: True
    persistent_workers: True

  encoders:               
    # # DINO
    # vision_ckpt: "facebook/dinov2-base"
    # text_ckpt:   "sentence-transformers/all-MiniLM-L6-v2"
    # # text_ckpt:   "sentence-transformers/paraphrase-MiniLM-L3-v2"

    # CLIP
    vision_ckpt: "openai/clip-vit-base-patch32"
    text_ckpt: "openai/clip-vit-base-patch32"

  model:
    d_model: 768          # CLS width of dinov2-base
    max_seq_len: 128
    n_layers: 8
    n_heads: 12
    dropout: 0.1
    horizon: 8
    n_obs_steps: 6
    max_rewind_steps: 3
    frame_gap: 10
    state_dim: 14
    no_state: True
    dense_annotation: False # check the rule inside the dataset class to allign with progress
    resume_training: True
    model_path: "/nfs_us/david_chen/reward_model_ckpt/dish_unloading/2025-09-13/11-14-01/unload_dish/checkpoints"

    # Dense anno
    anno_type: "sparse"
    num_classes: 3 # num_classes = num_stage 
    annotation_list: [
        "grab the dish",
        "place the dish",
    ]

  optim:
    lr: 5e-5
    weight_decay: 5.0e-3
    betas: [0.9, 0.95]
    eps: 1.0e-8
    warmup_steps: 1000
    total_steps: 100_000

  train:
    num_epochs: 2
    grad_clip: 1.0
    log_every: 50        # steps
    eval_every: 1        # epochs
    save_every: 2_000     # steps
    val_portion: 0.1     # fraction of episodes for validation
    rollout_every: 10     # epoch
    rollout_steps: 10    # steps per rollout

  eval:
    run_times: 50        # number of rollouts
    video_run_times: 20 # number of episodes to evaluate in video
    raw_data_run_times: 36
    eval_frame_gap: 1
    
    ckpt_path: "/nfs_us/david_chen/reward_model_ckpt/dish_unloading/2025-09-13/11-14-01/unload_dish/checkpoints"
    raw_data_dir: ""

    
